# Generated by Django 5.0.6 on 2024-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="b963e921", max_length=8, unique=True),
        ),
    ]
