# Generated by Django 5.0.6 on 2024-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="0fdc4956", max_length=8, unique=True),
        ),
    ]
