# Generated by Django 5.0.6 on 2024-06-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="55D4B08C", max_length=8, unique=True),
        ),
    ]
