# Generated by Django 5.0.6 on 2024-06-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(default="E117269F", max_length=8, unique=True),
        ),
    ]
